title: Cyrus Zhang's personal blog
description: "I'm a person"
owner_name: Cyrus Zhang
github_username: GuyYueFangYUan
github_repo: "student" 
baseurl: "/student"
future: true

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

# Minima options won't apply here since you're using Cayman.
# Remove or switch to minima theme if you want nav_pages, skin, etc.
