title: "Cyrus Zhang's personal blog"
description: Hi
owner_name: "Cyrus Zhang"

baseurl: "/student"
# Optional: if you want canonical URLs
# url: "https://guyyuefangyuan.github.io"

remote_theme: "jekyll/minima"
plugins:
  - jekyll-remote-theme

minima:
  skin: dark

# Minima uses header_pages (not nav_pages)
header_pages:
  - navigation/about.md
  - navigation/blog.md
  - navigation/search.md

social_links:
  - platform: github
    user_url: "https://github.com/nighthawkcoders"
  - platform: x
    user_url: "https://x.com/NighthawkCoding/"
  - platform: youtube
    user_url: "https://www.youtube.com/@nighthawkcodingsociety2868"


