title: Cyrus Zhang's personal blog
description: "I'm a person"
owner_name: Cyrus Zhang
github_username: GuyYueFangYUan
github_repo: "student" 
baseurl: "/student"
future: true

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

minima:
  skin: leaf
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" }
  nav_pages:
    - navigation/blog.md
    - navigation/search.md
